apiVersion: v1
kind: Pod
spec:
  containers:
  - name: awscli
    image: amazon/aws-cli:latest
    command:
    - sleep
    args:
    - 10000000
    resources:
      requests:
        cpu: 256m
        memory: 1G
      limits:
        cpu: 256m
        memory: 1G
  restartPolicy: Never
